Vagrant.configure("2") do |config|
    config.vm.box = "gusztavvargadr/windows-10"
    config.vm.hostname = "ws-1"
    config.vm.network "private_network", ip: "10.10.1.101"

    config.vm.provider "virtualbox" do |vb|
        vb.gui = true
        vb.memory = "4096"
        vb.cpus = "2"
    end

    config.vm.provision "shell", inline: <<-'POWERHSELL'
        Set-TimeZone "Asia/Dubai"
        Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

        choco install -y firefox
        choco install -y 7zip

        Install-ChocolateyPinnedTaskBarItem "${env:ProgramFiles(x86)}\Mozilla Firefox\firefox.exe"

    POWERHSELL

end