# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.box_check_update = false
  config.vm.network "forwarded_port", guest: 443, host: 8080
  config.vm.hostname = "wazuh"
  config.vm.network "private_network", ip: "192.168.10.1"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "8192"
    vb.cpus = 4
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y curl
    curl -sO https://packages.wazuh.com/4.5/wazuh-install.sh && bash ./wazuh-install.sh -a
  SHELL
end
