# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "archlinux/archlinux"
  config.vm.box_check_update = true
  config.vm.hostname = "linux-host-art-2"
  config.vm.network "private_network", ip: "192.168.10.3"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "4096"
    vb.cpus = "2"
  end
  config.vm.provision "shell", inline: <<-SHELL
    pacman -Syu
  SHELL
end
