
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "wazuh"
  config.vm.network "private_network", ip: "10.10.1.10"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "4096"
    vb.cpus = "2"
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt update
    apt install -y curl
    curl -fsSL https://tailscale.com/install.sh | sh
    curl -sO https://packages.wazuh.com/4.5/wazuh-install.sh && bash ./wazuh-install.sh -a
  SHELL
end
